Add German Translations
ziglang/www.ziglang.org pull request #113
Opened 2021-02-12 13:08 UTC by InterplanetaryEngineer

Translated the pages Index, Learn, Getting Started, Overview, Samples, Tools, Why Zig, and ZSF.

Some of the translations may be a bit too literal, but hopefully not grammatically wrong; this took a bit longer than I expected, and I couldn't be bothered to rephrase every sentence into the most elegant prose.

The reader is addressed in the informal form, which I found most fitting for an open-source project talking to its community, but one might also argue that the formal pronouns are more appropriate for an organization addressing potential sponsors. I would like to hear another German reader's opinion on this.

I have converted most section references from absolute to relative links (`[...](https://ziglang.org/#Stack-traces-on-all-targets)` -> `[...](#stacktraces-auf-allen-targets)`), but may have overlooked one or two.

2021-02-15 15:57 UTC, kristoff-it commented
Thank you very much! I've pinged @MasterQ32 to give a read to the German phrasing. I'll soon do a pass to check links.

2021-02-15 18:21 UTC, kristoff-it requested changes
Just minor changes, sorry I realize I left a couple of foot guns here and there.

2021-02-15 18:21 UTC, kristoff-it commented on content/_index.de.md
> +{{< slogan get_started="EINFÜHRUNG" docs="Dokumentation" notes="Änderungen">}}
```suggestion
{{< slogan get_started="EINFÜHRUNG" docs="Dokumentation" notes="Änderungen" lang="de">}}
```

2021-02-15 18:21 UTC, kristoff-it commented on content/learn/getting-started.de.md
> +<img src="../../heart.svg" style="vertical-align:middle; margin-right: 5px">.
```suggestion
<img src="/heart.svg" style="vertical-align:middle; margin-right: 5px">.
```

2021-02-15 18:21 UTC, kristoff-it commented on content/zsf/index.de.md
> +     <img src="../pex-dark.svg">
```suggestion
     <source srcset="/pex-white.svg" media="(prefers-color-scheme: dark)">
     <img src="/pex-dark.svg">
```

2021-02-15 18:21 UTC, kristoff-it commented on content/zsf/index.de.md
> +![](../aws.png)
```suggestion
![](/lavatech.png)
![](/dropbox.png)
![](/aws.png)
```

2021-02-21 18:36 UTC, MasterQ32 requested changes
Made most comments in german, there are mostly some formulations that need change (most time with an improved formulation).

If those are changed, we can go live with this :+1:

2021-02-21 18:36 UTC, MasterQ32 commented on content/learn/samples.de.md
> +Der `std.GeneralPurposeAllocator` kann Doppel-Freigabe und Speicherlecks nachverfolgen.
`std.heap.GeneralPurposeAllocator` cc @kristoff-it

2021-02-21 18:36 UTC, MasterQ32 commented on content/learn/why_zig_rust_d_cpp.de.md
> +Eigene Allocators machen manuelle Speicherverwaltung kinderleicht. Zig hat einen Debug-Allocator, der Speichersicherheit bei Use-after-free und Double-free garantiert. Er detektiert und logt automati
Allokatoren, nicht Allocators

2021-02-21 18:36 UTC, MasterQ32 commented on content/learn/why_zig_rust_d_cpp.de.md
> +Zig kann nicht nur C- oder C++-Code ersetzen, sondern auch autotools, cmake, make, scons, ninja usw. Und obendrein bietet es (bald™) einen Paketmanager für native Abhängigkeiten. Dieses Build-System
Dieses Build-System ist auch für Projekte relevant, deren gesamte Codebasis aus C oder C++ besteht.

2021-02-21 20:04 UTC, InterplanetaryEngineer commented on content/learn/getting-started.de.md
> +In der Praxis **liegen Zigs Releases weit auseinander und werden bei der momentanen Entwicklungsgeschwindigkeit irgendwann veraltet**.
"irgendwann" is the faithful translation of the "eventually" on the English page. Is that one also incorrect?

2021-02-21 20:07 UTC, InterplanetaryEngineer commented on content/learn/getting-started.de.md
> +[ziglearn.org](https://ziglearn.org) verfolgen aus obigen Gründen den Master-Branch.
The German (Git manual)[https://git-scm.com/book/de/v2/Git-Branching-Remote-Branches] also translates "track" as "vefolgen"

2021-02-21 20:31 UTC, InterplanetaryEngineer commented on content/learn/_index.de.md
> +Dies sind Einführungen in Zig für Programmierer mit verschiedenen Vorkenntnissen.
Der Satz ist so grammatikalisch in Ordnung, das "alles" ist redundant, und "Hier sind" hört sich ungelenk an...

2021-02-21 20:41 UTC, MasterQ32 commented on content/learn/getting-started.de.md
> +In der Praxis **liegen Zigs Releases weit auseinander und werden bei der momentanen Entwicklungsgeschwindigkeit irgendwann veraltet**.
Yeah, but i was going less for a word-by-word translation and brought more intent into the sentence. @kristoff-it *eventually* might actually be "too slow" for a time span of 1 to 6 weeks when releases are 6 months apart

2021-02-21 20:42 UTC, MasterQ32 commented on content/learn/getting-started.de.md
> +[ziglearn.org](https://ziglearn.org) verfolgen aus obigen Gründen den Master-Branch.
Yeah, i know. But "verfolgen" just sounds weird and is less clear imho

2021-02-21 20:43 UTC, MasterQ32 commented on content/learn/_index.de.md
> +Dies sind Einführungen in Zig für Programmierer mit verschiedenen Vorkenntnissen.
Da, aber da die Seite informell formuliert ist und nicht siezt, finde ich einen etwas lockerern Sprachstil angebrachter. Das ist aber denke ich Geschmackssache

2021-02-22 09:24 UTC, InterplanetaryEngineer commented on content/learn/_index.de.md
> +Dies sind Einführungen in Zig für Programmierer mit verschiedenen Vorkenntnissen.
Das stimmt allerdings. Ist die letzte Fassung:

> Einige Seiten zum Einstieg in Zig [...]:

so okay?

2021-02-22 09:56 UTC, MasterQ32 reviewed
It's good now from my side.

2021-02-22 09:56 UTC, MasterQ32 approved these changes

2021-02-22 18:40 UTC, kristoff-it commented
Thank you very much!

2021-02-22 18:40 UTC, merged