add zh translation
ziglang/www.ziglang.org pull request #95
Opened 2021-01-13 14:57 UTC by codehz

2021-01-13 15:34 UTC, codehz commented
There should be no more invalid links

2021-01-13 22:39 UTC, kristoff-it commented
Thank you for this translation, I suspect it's going to be one of the most popular ones :)

Let me know when you're done working and want me to review (tag me in a comment, or ask for a review, whichever way you prefer) and please don't esitate to ask for help if something is not clear.

Also please make sure to preview your code locally, I can be fairly confident most things are ok when using a latin alphabet but there might be some problematic situations that I'm not aware of. I'll be happy to solve any such situation for you in that case.

2021-01-14 05:51 UTC, codehz commented
Current Progress:
```
                   | EN | IT | ZH  
-------------------+----+----+-----
  Pages            | 20 | 10 | 14  
  Paginator pages  |  0 |  0 |  0
  Non-page files   | 40 |  1 |  1
  Static files     | 11 | 11 | 11
  Processed images |  0 |  0 |  0
  Aliases          |  5 |  0 |  0
  Sitemaps         |  2 |  1 |  1
  Cleaned          |  0 |  0 |  0
```

2021-01-14 06:08 UTC, Prince213 requested changes

2021-01-14 06:08 UTC, Prince213 commented on content/zsf/index.zh.md
> +以下公司向Zig软件基金会免费提供部分服务。
```suggestion
以下公司向 Zig 软件基金会免费提供部分服务。
```

2021-01-14 06:08 UTC, Prince213 commented on content/_index.zh.md
> +title: 主页
```suggestion
title: "主页"
```

2021-01-14 06:08 UTC, Prince213 commented on content/_index.zh.md
> +- 使用可移植的向量类型表达SIMD指令。
```suggestion
- 使用可移植的向量类型表达 SIMD 指令。
```

2021-01-14 06:08 UTC, Prince213 commented on content/_index.zh.md
> +以下公司为Zig软件基金会提供直接的资金支持。
```suggestion
以下公司为 Zig 软件基金会提供直接的资金支持。
```

2021-01-14 06:08 UTC, Prince213 commented on content/learn/getting-started.zh.md
> +title: 快速入门
```suggestion
title: "快速入门"
```

2021-01-14 06:08 UTC, Prince213 commented on content/learn/overview.zh.md
> +- Zig 不仅可以为这些目标生成机器代码，而且标准库的跨平台抽象也有这些目标的实现。因此，写一个不依赖 libc 的纯 Zig 应用是很实用的。
```suggestion
- Zig 不仅可以为这些目标生成机器代码，而且标准库的跨平台抽象也有这些目标的实现。因此，写一个不依赖 libc 的纯 Zig 应用是可行的。
```

2021-01-14 06:08 UTC, Prince213 commented on content/learn/overview.zh.md
> +没有**隐藏的控制流**，没有隐藏的内存分配，没有预处理器，也没有宏。如果 Zig 代码看起来不像是跳开调用一个函数，那么它就不是。这意味着你可以确定下面的代码只调用 `foo()`，然后调用 `bar()`，这一点是可以保证的，而不需要知道任何东西的类型：
```suggestion
没有**隐藏的控制流**，没有隐藏的内存分配，没有预处理器，也没有宏。如果 Zig 代码看起来不像是调用一个函数，那么它就不是。这意味着你可以确定下面的代码只调用 `foo()`，然后调用 `bar()`，这一点是可以保证的，而不需要知道任何东西的类型：
```

2021-01-14 06:08 UTC, Prince213 commented on content/news/_index.zh.md
> +title: 新闻
```suggestion
title: "新闻"
```

2021-01-14 06:08 UTC, Prince213 commented on content/zsf/index.zh.md
> +ZSF是一个小组织，并且有效地利用了货币资源。我们的计划是保持这种方式，但我们确实想把我们的无偿志愿者变成有偿的维护者，以帮助合并拉取请求，使 1.0 的进展更加迅速。ZSF 作为一个非营利性的组织，其目的就是为了造福于人们。我们正在尝试让开源维护者为他们的时间获得报酬。
```suggestion
ZSF 是一个小组织，并且有效地利用了货币资源。我们的计划是保持这种方式，但我们确实想把我们的无偿志愿者变成有偿的维护者，以帮助合并拉取请求，使 1.0 的进展更加迅速。ZSF 作为一个非营利性的组织，其目的就是为了造福于人们。我们正在尝试让开源维护者为他们的时间获得报酬。
```

2021-01-14 06:08 UTC, Prince213 commented on content/zsf/index.zh.md
> +- [Benevity](https://benevity.com) （如果您的雇主想要捐款，建议使用这个方法!）
```suggestion
- [Benevity](https://benevity.com) （如果你的雇主想要捐款，建议使用这个方法！）
```

2021-01-14 06:08 UTC, Prince213 commented on content/zsf/index.zh.md
> +以下公司通过捐赠 1000 美元/月以上的方式，为Zig软件基金会提供直接的资金支持。
```suggestion
以下公司通过捐赠 1000 美元/月以上的方式，为 Zig 软件基金会提供直接的资金支持。
```

2021-01-14 07:39 UTC, Prince213 requested changes

2021-01-14 07:39 UTC, Prince213 commented on content/learn/_index.zh.md
> +一篇关于构建 Zig 自托管编译器的博客文章, 也被[ lwn.net 的一篇文章所介绍](https://lwn.net/Articles/833400/).
```suggestion
一篇关于构建 Zig 自托管编译器的博客文章，也被[ lwn.net 的一篇文章所介绍](https://lwn.net/Articles/833400/)。
```

2021-01-14 07:39 UTC, Prince213 commented on content/learn/_index.zh.md
> +[Andrew Kelley](https://andrewkelley.me) 介绍Zig及其理念的视频。
```suggestion
[Andrew Kelley](https://andrewkelley.me) 介绍 Zig 及其理念的视频。
```

2021-01-14 07:39 UTC, Prince213 commented on content/learn/getting-started.zh.md
> +要在 Windows 上设置 PATH，请在 Powershell 中运行以下**任一**代码片段:
```suggestion
要在 Windows 上设置 PATH，请在 PowerShell 中运行以下**任一**代码片段:
```

2021-01-14 07:39 UTC, Prince213 commented on content/learn/getting-started.zh.md
> +选择您是要在全系统级别上应用此更改 （需要在有管理员权限的情况下运行Powershell）
```suggestion
选择你是要在系统级别上应用此更改 （需要在有管理员权限的情况下运行 PowerShell）
```

2021-01-14 07:39 UTC, Prince213 commented on content/learn/getting-started.zh.md
> +还是只针对您的用户，**并确保更改代码以指向Zig副本所在的位置**。
```suggestion
还是只针对你使用的用户，**并确保更改代码以指向 Zig 所在的位置**。
```

2021-01-14 07:39 UTC, Prince213 commented on content/learn/getting-started.zh.md
> +系统级安装 (**管理员** Powershell):
```suggestion
系统级安装 (**管理员** PowerShell):
```

2021-01-14 07:39 UTC, Prince213 commented on content/learn/getting-started.zh.md
> +用户级安装 (Powershell):
```suggestion
用户级安装 (PowerShell):
```

2021-01-14 07:39 UTC, Prince213 commented on content/learn/getting-started.zh.md
> +运行完毕后重启您的 Powershell 实例。
```suggestion
运行完毕后重启你的 PowerShell 实例。
```

2021-01-14 07:39 UTC, Prince213 commented on content/learn/getting-started.zh.md
> +<img src="../../heart.svg" style="vertical-align:middle; margin-right: 5px">.
```suggestion
<img src="../../heart.svg" style="vertical-align:middle; margin-right: 5px">。
```

2021-01-14 07:39 UTC, Prince213 commented on content/learn/overview.zh.md
> +请注意，只有[一级支持](#一级支持)目标已被彻底测试。我们有计划增加[更多的 libc](https://github.com/ziglang/zig/issues/514)（包括 Windows 平台），并增加[针对所有 libc 的测试覆盖率](https://github.com/ziglang/zig/issues/2058)。
```suggestion
请注意，只有[一级支持](#一级支持)目标得到了彻底测试。我们有计划增加[更多的 libc](https://github.com/ziglang/zig/issues/514)（包括 Windows 平台），并提高[对所有 libc 的测试覆盖率](https://github.com/ziglang/zig/issues/2058)。
```

2021-01-14 07:39 UTC, Prince213 commented on content/learn/why_zig_rust_d_cpp.zh.md
> +你不仅可以用 Zig 代码代替 C 或 C++ 代码，还可以用 Zig 代替 autotools、cmake、make、scons、ninja 等。而在此之上，它（将）提供一个本地依赖的包管理器。这个构建系统的目的是为了使得即使一个项目的全部代码库都是 C 或 C++ 也能适用。
```suggestion
你不仅可以用 Zig 代码代替 C 或 C++ 代码，还可以用 Zig 代替 autotools、cmake、make、scons、ninja 等。而在此之上，Zig（将）提供一个本地依赖的包管理器。这个构建系统的目的是为了使得即使一个项目的全部代码库都是 C 或 C++ 也能适用。
```

2021-01-14 09:26 UTC, Prince213 approved these changes

2021-01-14 11:40 UTC, codehz commented
@kristoff-it I think it's time to merge

2021-01-14 18:17 UTC, kristoff-it commented
Hi @codehz, wow amazing work. I can't comment on the content itself but everything looks good from what I can tell and all links are working. 

I'll merge a fix for #99 soon. After we're done with that I'll be happy to merge everyhing.

Thank you very much again. Amazing work.

2021-01-14 22:51 UTC, kristoff-it commented
There are 3 new variables in `i18n/en.toml`, pull from master to obtain them.  I'll list them here for convenience: 

```
[slogan-latest-release]
other = "Latest Release: &nbsp; <b>{{ . }}</b>"


[downloads-heading]
other = "Releases"

[downloads-install-from-pkg-manager]
other = "You can also <a href=\"https://github.com/ziglang/zig/wiki/Install-Zig-from-a-Package-Manager\"> install Zig from a package manager</a>."

[downloads-json]
other = "There is a <a href=\"https://ziglang.org/download/index.json\">JSON version of this page</a>."
```

Finally, please take a look at this commit, it deleted one sentence from `overvirew.md`:  https://github.com/ziglang/www.ziglang.org/commit/925f0dec9b5d1a30ae9f2e54426b5476b6495674

After this, we're done. Thank you again for your work.

2021-01-15 05:35 UTC, codehz commented
ohhh, I messed with git-merge, you may want to use squash and merge... @kristoff-it

2021-01-15 11:15 UTC, codehz commented
try fix it by cherry-pick

2021-01-15 11:29 UTC, codehz commented
rebased and no conflict now

2021-01-15 15:32 UTC, merged

2021-01-15 15:33 UTC, kristoff-it commented
Awesome work, thanks again. If you happen by any of the Discord communities make sure to say hi :)